module.exports = {
  INVALID_LOGIN: 'INVALID_LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGGED_OUT: 'LOGGED_OUT',
  SIGNUP_ERROR: 'SIGNUP_ERROR',
  SIGNUP_CLEAR: 'SIGNUP_CLEAR',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_STEP: 'SIGNUP_STEP'
};
